environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "10"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  # Debugging
  - node --version
  - npm --version
  # Run tests
  - npm test

# Don't actually build.
build: off
